### ISSUE TITLE
step to install it, use it?

### ISSUE THREAD

**Issue by souhaiebtar** [depwaswho/vuestic-laravel#1]
would you please add the steps required to install it ?

**Comment by Baltimer** [comment]
You have to clone it and:
`composer install
npm install
cp .env.example .env
php artisan migrate
php artisan key:generate`

**Comment by depwaswho** [comment]
Closing this issue as it is fixed in [c205c44](https://github.com/depwaswho/vuestic-laravel/commit/c205c4410d482482d0f11b580ddf25c7534f9b0f).
